# Generated by Django 2.2.10 on 2020-05-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200516_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='info',
            field=models.TextField(default='SOME STRING', max_length=140),
        ),
    ]
