# Generated by Django 2.2.10 on 2020-05-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(help_text='put your last  image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='info',
            field=models.TextField(default='Writte about your page', max_length=140),
        ),
    ]
