# Generated by Django 2.2.10 on 2020-05-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200516_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.ImageField(default='', help_text='put your last  image', upload_to=''),
        ),
    ]
