# Generated by Django 2.2.10 on 2020-05-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200517_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='AvailabilityOccurrence',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomReservation',
        ),
    ]
