# Generated by Django 2.2.10 on 2020-05-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customer_reservation_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='party',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
