# Generated by Django 2.2.10 on 2020-05-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200518_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Professional'), ('SW', 'Normal'), ('OW', 'At home')], max_length=2),
        ),
    ]
