# Generated by Django 2.2.10 on 2020-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200518_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'Expensive'), ('S', 'Normal'), ('D', 'Cheap')], max_length=1),
        ),
    ]
