# Generated by Django 2.2.10 on 2020-05-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_item_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image5',
            field=models.ImageField(default='', help_text='put your last  image', upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='image6',
            field=models.ImageField(default='', help_text='put your last  image', upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='image7',
            field=models.ImageField(default='', help_text='put your last  image', upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='image8',
            field=models.ImageField(default='', help_text='put your last  image', upload_to=''),
        ),
    ]
