# Generated by Django 2.2.10 on 2020-06-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200522_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(blank=True, default='', help_text='put your first  image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, default='', help_text='put your second  image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, default='', help_text='put your third  image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image4',
            field=models.ImageField(blank=True, default='', help_text='put your last  image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image5',
            field=models.ImageField(blank=True, default='', help_text='put your last  image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image6',
            field=models.ImageField(blank=True, default='', help_text='put your last  image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image7',
            field=models.ImageField(blank=True, default='', help_text='put your last  image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image8',
            field=models.ImageField(blank=True, default='', help_text='put your last  image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='info',
            field=models.TextField(blank=True, default='Writte about your page', max_length=140),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
