# Generated by Django 2.2.10 on 2020-06-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='categoryUser',
            field=models.CharField(choices=[('К', 'Клиент'), ('М', 'Мастер')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
