# Generated by Django 2.2.10 on 2020-06-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_order_categoryuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='',
                                            help_text='put your principal image', upload_to='')),
            ],
        ),
    ]
