# Generated by Django 2.2.10 on 2020-06-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
