# Generated by Django 2.2.10 on 2020-06-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
