# Generated by Django 2.2.10 on 2020-06-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200606_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
