# Generated by Django 2.2.10 on 2020-06-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_image_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', help_text='put your principal image', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(blank=True, default='', help_text='put your first  image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, default='', help_text='put your second  image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, default='', help_text='put your third  image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image4',
            field=models.ImageField(blank=True, default='', help_text='put your last  image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image5',
            field=models.ImageField(blank=True, default='', help_text='put your last  image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image6',
            field=models.ImageField(blank=True, default='', help_text='put your last  image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image7',
            field=models.ImageField(blank=True, default='', help_text='put your last  image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image8',
            field=models.ImageField(blank=True, default='', help_text='put your last  image', null=True, upload_to=''),
        ),
    ]
