# Generated by Django 2.2.10 on 2020-06-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200607_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Professional'), ('SW', 'Normal'), ('OW', 'At home')], max_length=2, verbose_name='Категория мастера'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стоимость со скидкой (необязательно)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Обложка салона'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Примеры дизайнов'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='info',
            field=models.TextField(blank=True, max_length=140, verbose_name='Описание салона'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='1591496974', verbose_name='Ссылка на салон'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Подтверждён'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название салона'),
        ),
    ]
