# Generated by Django 2.2.10 on 2020-06-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200607_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='1591501339', verbose_name='Ссылка на салон'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='', upload_to='media/', verbose_name='Обложка'),
        ),
    ]
