# Generated by Django 2.2.10 on 2020-06-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200607_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='slug',
        ),
        migrations.AddField(
            model_name='new',
            name='slug',
            field=models.SlugField(default='1591501456', verbose_name='Ссылка на статью'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='1591501456', verbose_name='Ссылка на салон'),
        ),
    ]
