# Generated by Django 2.2.10 on 2020-06-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20200618_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='autor',
            new_name='auth',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='autor',
            new_name='auth',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='autor',
            new_name='auth',
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='1592443261', verbose_name='Ссылка на салон'),
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(default='1592443261', verbose_name='Ссылка на статью'),
        ),
    ]
