# Generated by Django 2.2.10 on 2020-06-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200618_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='text',
            field=models.TextField(blank=True, max_length=140, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='1592448530', verbose_name='Ссылка на салон'),
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(default='1592448530', verbose_name='Ссылка на статью'),
        ),
    ]
