# Generated by Django 2.2.10 on 2020-06-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20200618_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Салон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='1592449455', verbose_name='Ссылка на салон'),
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(default='1592449455', verbose_name='Ссылка на статью'),
        ),
    ]
