# Generated by Django 2.2.10 on 2020-06-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200618_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='host',
            field=models.CharField(default=0, max_length=140, verbose_name='Мастер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='saloon',
            field=models.CharField(default=None, max_length=140, verbose_name='Название салона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Обычный'), ('H', 'На дому')], max_length=2, verbose_name='Категория мастера'),
        ),
        migrations.AlterField(
            model_name='item',
            name='info',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Описание салона'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='1592526004', verbose_name='Ссылка на салон'),
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(default='1592526004', verbose_name='Ссылка на статью'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='slug',
            field=models.CharField(max_length=140, verbose_name='Ссылка на салон'),
        ),
    ]
