# Generated by Django 2.2.10 on 2020-06-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20200619_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='slug',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='1592532937', verbose_name='Ссылка на салон'),
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(default='1592532937', verbose_name='Ссылка на статью'),
        ),
    ]
