# Generated by Django 2.2.10 on 2020-06-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20200619_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='date',
        ),
        migrations.AlterField(
            model_name='recording',
            name='text',
            field=models.TextField(blank=True, max_length=140, verbose_name='Расскажите о предпочтительном времени, добавьте дополнительную информацию'),
        ),
    ]
