# Generated by Django 2.2.10 on 2020-06-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20200619_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='services',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Список услуг'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Обычный'), ('H', 'На дому')], max_length=2, verbose_name='Категория мастера*'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стоимость со скидкой'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Обложка салона*'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Стоимость*'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название салона*'),
        ),
    ]
