# Generated by Django 2.2.10 on 2020-06-22 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20200622_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['slug']},
        ),
    ]
